import type { Metadata } from "next";
import "./globals.css";
import { Navbar } from "@/components/navbar";
import { BreadcrumbNav } from "@/components/navbar/breadcrumbNav";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <div className="max-w-[960px] mx-auto px-4 pt-8 pb-28">
          <BreadcrumbNav autoGenerate className="mb-5" />
          {children}
        </div>
        <Navbar />
      </body>
    </html>
  );
}
